openapi: 3.0.1
info:
  title: Colors API
  description: API description in OpenAPI 3.0 format
  version: 0.0.1

tags:
  - name: Images
    description: Image urls endpoints
paths:
  /storage/v1/images/{imageName}:
    get:
      tags:
        - Images
      summary: Get urls by image's names
      description: The endpoint get urls by image's names
      operationId: getImageByName
      parameters:
        - in: path
          name: imageName
          schema:
            type: string
            description: image's name
          required: true
      responses:
        '200':
          description: Success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ImageUrl'
        '503':
          description: Service Unavailable
        '404':
          $ref: '#/components/responses/NotFound'

components:
  responses:
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ImageUrl:
      type: object
      description: Image`s urls
      properties:
        imageUrl:
          type: string
          example: https://host.com/image.png
      required:
        - imageUrl

    ErrorResponse:
      type: object
      description: Image`s urls
      properties:
        status:
          type: string
          example: 404
        detail:
          type: string
          example: NotFound
      required:
        - status
        - detail
