springdoc.swagger-ui.enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/retail
    username: pgusr
    password: pgpwd
  flyway:
    enabled: false

rest:
  client:
    colors:
      base-url: http://localhost:8081/colors

auth:
  users:
    - username: user
      password: ${LOCAL_PASSWORD:user}
      roles: USER
    - username: admin
      roles: ADMIN
      password: ${LOCAL_PASSWORD:admin}


