management.endpoints.web.exposure.include: "health,info,metrics"

springdoc.swagger-ui.enabled: true

logging:
  level:
    root: INFO

server:
  port: ${SERVER_PORT:8080}
  servlet.context-path: /retail

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        globally_quoted_identifiers: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration

rest:
  client:
    colors:
      base-url: http://${MOCKED_SERVICES_HOST:localhost}:${MOCKED_SERVICES_PORT:8081}/colors

resilience4j:
  circuitbreaker:
    instances:
      imagesCircuit:
        minimumNumberOfCalls: 5
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 500
        failureRateThreshold: 55
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 30000
  retry:
    instances:
      imagesRetry:
        maxAttempts: 3
        waitDuration: 200
        fail-after-max-attempts: true

images:
  default:
    url: https://www.demyhealth.com/storage/media/2/default-product-image.png