openapi: 3.0.1
info:
  title: Retail API
  description: API description in OpenAPI 3.0 format
  version: 0.0.1

servers:
  - url: http://localhost:8080/retail

#TAGS
#=======================================================================================================================
tags:
  - name: Security
    description: Token retrieval

  - name: Products
    description: Products endpoint

  - name: Orders
    description: Orders endpoints

  - name: Cart
    description: Cart management endpoints

#ENDPOINTS
#=======================================================================================================================
paths:
  /auth/sign-in:
    post:
      tags:
        - Security
      summary: Sign in user
      operationId: signIn
      description: The endpoint sign in the user to the DB.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /auth/sign-up:
    post:
      tags:
        - Security
      summary: Register a new user
      operationId: signUp
      description: The endpoint registers a new user to the DB.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '201':
          description: Successful registration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '409':
          $ref: '#/components/responses/Conflict'

  /v1/orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by id
      operationId: getOrderById
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
            description: Id of the order
            format: uuid
          example: '8efbee82-8a0c-407a-a4c0-16bbad40a23e'
      responses:
        '200':
          description: Order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
  /v1/users/{userId}/orders:
    post:
      tags:
        - Orders
      summary: Place an order
      parameters:
        - $ref: '#/components/parameters/UserId'
      operationId: placeOrder
      security:
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOrderRequest'
      responses:
        '201':
          description: Order is created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlaceOrderResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
    get:
      tags:
        - Orders
      summary: View the orders history
      operationId: getOrdersByUser
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/UserId'
        - in: query
          name: lang
          required: false
          schema:
            type: string
            default: ua
            nullable: false
            example: ua
        - $ref: '#/components/parameters/Pageable'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOrder'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /v1/products:
    get:
      tags:
        - Products
      summary: Get list of products
      description: The endpoint for getting all products from the database.
      operationId: getProducts
      parameters:
        - in: query
          name: lang
          required: false
          schema:
            type: string
            default: en
            nullable: false
            example: ua
          description: The language code for the product information (e.g., 'ua' for Ukrainian).
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
          description: Page request parameters for pagination and sorting.
      responses:
        '200':
          description: Short information about all products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageProducts'

  /v1/users/{userId}/cart/{productId}:
    post:
      tags:
        - Cart
      summary: Add products to the cart
      description: The endpoint for adding a product to the user's shopping cart.
      operationId: addProductToCart
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            format: uuid
            example: '8efbee82-8a0c-407a-a4c0-16bbad40a23e'
          description: The id of the product which is added to the cart
        - $ref: '#/components/parameters/UserId'
      responses:
        '201':
          description: The card with added products was created
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '409':
          description: Conflict - Product already exists in the cart

#COMPONENTS
#=======================================================================================================================
components:

  #PARAMETERS
  #=======================================================================================================================
  parameters:
    Pageable:
      name: pageable
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/Pageable'
    UserId:
      in: path
      name: userId
      required: true
      schema:
        type: integer
        description: Id of the user
        format: int64
      example: '1'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  #RESPONSES
  #=======================================================================================================================
  responses:
    CreatedResponse:
      description: Resource created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreatedResponse'

    NotFoundResponse:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 404
            title: Not Found
            detail: The requested resource was not found

    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 409
            title: Conflict
            detail: The requested has conflict

    BadRequestResponse:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 400
            title: Bad Request
            detail: Invalid Request. Please, check the data in the request (QueryString Parameters and/or Body).

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorObject'
          example:
            status: 401
            title: Unauthorized
            detail: Unauthorized access to the resource

  #SCHEMAS
  #=======================================================================================================================
  schemas:
    Pageable:
      type: object
      properties:
        page:
          type: integer
          minimum: 0
          default: 0
        size:
          type: integer
          minimum: 1
          default: 8
        sort:
          type: array
          items:
            type: string

    AbstractPage:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
          default: 0
        totalPages:
          type: integer
          default: 0
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
        numberOfElements:
          type: integer
        size:
          type: integer
        empty:
          type: boolean
        content:
          type: array
          items: { }

    SignInRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: example@mail.com
        password:
          type: string
          format: password
          example: Qwerty12345!
          pattern: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&-_])[A-Za-z\d@$!%*#?&-_]{8,}$
          description: The password must contain at least 8 characters, one uppercase letter, one digit, and one special character.
      required:
        - email
        - password

    SignUpRequest:
      type: object
      properties:
        email:
          type: string
          format: email
          example: example@mail.com
        password:
          type: string
          format: password
          example: Qwerty12345
          pattern: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&-_])[A-Za-z\d@$!%*#?&-_]{8,}$
          description: The password must contain at least 8 characters, one uppercase letter, one digit, and one special character.
        firstName:
          type: string
          example: John
          minLength: 2
          maxLength: 50
          pattern: ^[a-zA-Zа-яА-ЯёЁіІїЇєЄ'’\-]+$
          description: First name must contain from 2 to 50 characters long and can only include Latin and Cyrillic letters, as well as apostrophes and hyphens.
        lastName:
          type: string
          example: Doe
          minLength: 2
          maxLength: 50
          pattern: ^[a-zA-Zа-яА-ЯёЁіІїЇєЄ'’\-]+$
          description: Last name must contain from 2 to 50 characters long and can only include Latin and Cyrillic letters, as well as apostrophes and hyphens.
      required:
        - email
        - password
        - firstName
        - lastName

    AuthTokenResponse:
      title: AuthTokenResponse
      type: object
      additionalProperties: false
      required:
        - token
      properties:
        token:
          type: string
      description: |
        Token claims description.            
        - `sub`: Subject of the token (email of the user)
        - `firstName`: First name of the user
        - `lastName`: First name of the user
        - `scope`: Role assigned to the user
        - `iss`: issuer(who created and signed this token)
        - `id`: id of the logged-in user
        - `exp`: Expiration time (timestamp)
        - `iat`: Issued at time (timestamp)
        
        Example JWT payload:
        
        ```json
        {
          "sub": "user@mail.com",
          "firstName": "user",
          "lastName": "user",
          "scope": "ROLE_USER",
          "iss": "self",
          "id": 2,
          "exp": 1720025093,
          "iat": 1720021493
        }
        ```
      example: eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIkFETUlOIl0sInN1YiI6ImRtaWtoYWlsb3ZpY2gwM0BnbWFpbC5jb20iLCJpYXQiOjE3MTU4MDIyNTQsImV4cCI6MTcxNTkxMDI1NH0.pRIMnAzcdcvd2HkveUlLtgM9iCeek1UGew4JEt3oRzmNB80p795KSl9Tx7P0zqytK5_aH3Q-ydmrWUVELHy7Cg

    CreatedResponse:
      title: CreatedResponse
      type: object
      additionalProperties: false
      required:
        - message
      properties:
        message:
          type: string
          description: Creation status message
          example: Resource successfully created

    ErrorObject:
      title: Unauthorized
      type: object
      additionalProperties: false
      properties:
        status:
          type: integer
          description: Error code
          minimum: 100
          maximum: 599
        title:
          type: string
          description: Error title
          maxLength: 100
        detail:
          type: string
          description: Details of the exception
      required:
        - status
        - title
        - detail

    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the order
        isPaid:
          type: boolean
          description: Indicates whether the order has been paid
        orderStatus:
          $ref: '#/components/schemas/OrderStatus'
        createdAt:
          type: string
          format: date-time
          description: The date and time when the order was created
        total:
          type: number
          format: decimal
          description: The total cost of the order
        receiver:
          $ref: '#/components/schemas/OrderReceiver'
        postAddress:
          $ref: '#/components/schemas/PostAddress'
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'

    OrderItem:
      type: object
      properties:
        price:
          type: number
          format: decimal
          description: Price of the individual item
        quantity:
          type: integer
          description: Quantity of the item ordered
        product:
          $ref: '#/components/schemas/ProductPreview'

    OrderReceiver:
      type: object
      properties:
        firstName:
          type: string
          description: Receiver's first name
        lastName:
          type: string
          description: Receiver's last name
        email:
          type: string
          description: Receiver's email address

    PostAddress:
      type: object
      properties:
        deliveryMethod:
          $ref: '#/components/schemas/DeliveryMethod'
        city:
          type: string
          description: City of the delivery address
        department:
          type: string
          description: Department or region of the delivery address

    OrderStatus:
      type: string
      enum:
        - IN_PROGRESS
        - SHIPPED
        - DELIVERED
        - COMPLETED
        - CANCELED
      description: The various statuses an order can have

    DeliveryMethod:
      type: string
      enum:
        - NOVA
        - UKRPOSHTA
      description: The delivery methods available for shipping the order

    PageOrder:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractPage'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/Order'
              description: List of orders in the page

    PageProducts:
      type: object
      allOf:
        - $ref: '#/components/schemas/AbstractPage'
        - type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/ProductPreview'

    ProductPreview:
      type: object
      properties:
        id:
          type: string
          example: '123e4567-e89b-12d3-a456-426614174000'
          description: Product Id.
        name:
          type: string
          example: APPLE iPhone
          description: Name of the product.
        description:
          type: string
          example: Device type, operation system, etc.
          description: Product description
        status:
          type: string
          enum:
            - AVAILABLE
            - END_SOON
            - ENDED
          example: AVAILABLE
          description: Status of the product's quantity
        tags:
          type: array
          description: List of tags associated with the product
          items:
            type: string
            example: category:electronics
            description: Tag title
        image:
          type: string
          example: https://example.com/image.jpg
          description: List of image URLs associated with the product.
        price:
          type: number
          format: float
          example: 999.99
          description: Price of the product

    PlaceOrderRequest:
      type: object
      properties:
        firstName:
          type: string
          example: Doe
          minLength: 2
          maxLength: 50
          pattern: ^[a-zA-Zа-яА-ЯёЁіІїЇєЄ'’\-]+$
          description: Last name must contain from 2 to 50 characters long and can only include Latin and Cyrillic letters, as well as apostrophes and hyphens.
        lastName:
          type: string
          example: Doe
          minLength: 2
          maxLength: 50
          pattern: ^[a-zA-Zа-яА-ЯёЁіІїЇєЄ'’\-]+$
          description: First name must contain from 2 to 50 characters long and can only include Latin and Cyrillic letters, as well as apostrophes and hyphens.
        email:
          type: string
          format: email
          example: example@mail.com
        deliveryMethod:
          $ref: '#/components/schemas/DeliveryMethod'
        city:
          type: string
          minLength: 2
          maxLength: 100
          description: city where department is located
          example: Lviv
        department:
          type: string
          minLength: 2
          maxLength: 100
          description: department of the post
          example: №1 Franka street, 7
      required:
        - city
        - deliveryMethod
        - department
        - email
        - firstName
        - lastName

    PlaceOrderResponse:
      type: object
      properties:
        orderId:
          type: string
          format: uuid
          example: '8efbee82-8a0c-407a-a4c0-16bbad40a23e'
          description: id of recently created order
      required:
        - orderId