name: code-verify

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  verify:
    name: Build and verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: code
        run: mvn -B verify -DskipITs

      - name: JaCoCo analyze
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: "code/jacoco-report-aggregate/target/site/jacoco-aggregate/jacoco.xml"
          output_level: detailed

          # Comma-separated list of one or more directories to scan for code
          # coverage, relative to the root of the project. Will include all .ps1
          # and .psm1 files under these directories recursively.
          #coverage_paths:

          # The name of the code coverage report object that will be attached
          # to the Workflow Run.  Defaults to the name
          # `COVERAGE_RESULTS_<datetime>` where `<datetime>` is in the form
          # `yyyyMMdd_hhmmss`.
          #coverage_report_name:

          # The title of the code coverage report that will be embedded in the
          # report itself, which defaults to the same as the
          # `code_coverage_report_name` input.
          #coverage_report_title:

          # Minimum allowed coverage percentage as an integer.
          minimum_coverage: 80

          # Fail the action when the minimum coverage was not met.
          #fail_below_threshold: true

          # If true, will skip attaching the Tests Result report to the
          # Workflow Run using a Check Run. Useful if your report has 65k
          # characters that is not accepted by Github REST and GraphQL APIs
          publish_only_summary: false
