name: code-verify

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
     - 'code/**'


jobs:
  verify:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Verify
        working-directory: code
        run: mvn -B clean verify -DskipITs

      - name: Analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        with:
          projectBaseDir: code
          args: >
            -Dsonar.projectKey="${{ github.event.repository.name }}" 
            -Dsonar.host.url="https://sonarcloud.io/" 
            -Dsonar.organization=idx-academy 
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.pullrequest.branch="${{ github.head_ref }}" 
            -Dsonar.pullrequest.base=${{ github.base_ref }} 
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }} 
            -Dsonar.qualitygate.wait=true 
            -Dsonar.qualitygate.timeout=300 
            -Dsonar.pullrequest.provider=GitHub 
            -Dsonar.pullrequest.github.repository="${{ github.repository }}" 
            -Dsonar.pullrequest.github.summary_comment=true 
            -Dsonar.newCode.referenceBranch="${{ github.base_ref }}
            -Dsonar.verbose=true
