name: code-mocked-services

on:
  push:
    paths:
      - 'code/orders-boot/src/test/resources/compose/mocks/**'
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  verify:
    name: Build mocked services and deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
      #name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'test'}}
    env:
      ENV: dev
      # ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'test'}}
      APP_NAME: mocked-services
      MOCKS_PATH: code/orders-boot/src/test/resources/compose/mocks
      ACR_REGISTRY: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
      
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        id: az-acr-login
        run: az acr login --name $ACR_NAME
        env:
          ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}

      - name: Get image name
        run: |
          IMAGE="${{ env.APP_NAME }}:$(echo "${{ github.sha }}" | cut -c1-8)"
          echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Create Dockerfile dynamically
        run: |
          echo "FROM wiremock/wiremock:3.6.0
          COPY ${MOCKS_PATH} /home/wiremock" > Dockerfile

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.ACR_REGISTRY }}/${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Push to Azure Container registry
        run: docker push ${{ env.ACR_REGISTRY }}/${{ env.IMAGE }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Checkout kustomize repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/k8s-app-manifests
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: k8s-app-manifests

      - name: Update Kubernetes resources
        run: |
          cd k8s-app-manifests/apps/env/${ENV}/mocked-services
          kustomize edit set image ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}=${{ env.ACR_REGISTRY }}/${{ env.IMAGE }}

      - name: Commit files
        run: |
          cd k8s-app-manifests
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update mocked-services image ${{ env.IMAGE }}"
          git push -u origin main
