name: code-maven-build

on:
  pull_request:
    branches: 
      - develop #TODO delete me
  push:
    paths:
     - 'code/**'
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'dev'}}
    env:
      APP_NAME: ${{ github.event.repository.name }}
      ACR_REGISTRY: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io

    steps:      
      - name: Checkout repository
        uses: actions/checkout@v4

    
        
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/k8s-app-manifests
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: k8s-app-manifests

      - name: Update Kubernetes resources
        run: |
          ENV=${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/develop' && 'dev' || 'dev'}}
          cd k8s-app-manifests/apps/env/${ENV}/backend
          kustomize edit set image ${{ env.ACR_REGISTRY }}/${{ env.APP_NAME }}=${{ env.ACR_REGISTRY }}/${{ env.IMAGE }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd k8s-app-manifests
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update backend image ${{ env.IMAGE }}"
          git push -u origin main