name: code-verify

on:
  push:
    paths:
      - 'code/**'
    branches:
      - develop
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
     - 'code/**'
    branches:
      - develop
      - main

jobs:
  verify:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: code
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar -DskipITs \
          -Dsonar.projectKey="${{ github.event.repository.name }}" \
          -Dsonar.host.url="https://sonarcloud.io/"  \
          -Dsonar.organization=idx-academy  \
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}  \
          -Dsonar.pullrequest.branch="${{ github.head_ref }}"  \
          -Dsonar.pullrequest.base=${{ github.base_ref }}  \
          -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}  \
          -Dsonar.qualitygate.wait=true  \
          -Dsonar.qualitygate.timeout=300  \
          -Dsonar.pullrequest.provider=GitHub  \
          -Dsonar.pullrequest.github.repository="${{ github.repository }}"  \
          -Dsonar.pullrequest.github.summary_comment=true